### ISSUE TITLE
과제 관련 문의드립니다.

### ISSUE THREAD

**Issue by ParkGail** [rebehayan/Yeongdeungpo2024#6]
안녕하세요 강사님

글로 설명이 어려워 하단에 이미지처럼
왼쪽으로 붙어버린 부분을 오른쪽으로 보내고싶은데요..
css에서 
.body-right {
    align-items: end; 사용

html에서는 
      <div class="body-right">
            <div class="body-right-title">
              <div>관리자</div>
              <div>2020-10-22</div>
              <div class="title-views">637</div>
            </div>

로 묶었는데... 안먹는 이유가 무엇인지 궁금 합니다 ;-;

![image](https://github.com/rebehayan/Yeongdeungpo2024/assets/167504651/4e557c3b-a4bd-4b00-9ef7-75de2791815f)

**html**

`

    <div class="title-all">
      <ul class="head-title">
        공지사항 -확인용
      </ul>
      <body>
        <div class="body-title">
          <div class="body-left-title">
            2월 출석체크 이벤트 단첨자 러닝 어카운트 지급 결과 안내
          </div>
          <div class="body-right">
            <div class="body-right-title">
              <div>관리자</div>
              <div>2020-10-22</div>
              <div class="title-views">637</div>
            </div>
          </div>
        </div>
    </div>

      
      <div>
        중소기업에 근무하는 리더 직급을 대상으로 한 인터뷰에서 "우리 회사는
        인재원이 있거나, 인사 교육 시스템이 있는 대기업과는 달리 리더 육성의
        '시스템'과 교육이 부족하다"라는 아쉬운 목소리를 자주 듣는다. 그런데
        부재를 아쉬워하긴 했지만 막상 교육과 관련해서 기회가 있더라도 바빠서
        참여할 수 없었거나 우리 조직과 상황에 특화된 내용이 아닌 다양한
        구성원들이 모인 집합 형태의 외부 교육은 큰 도움을 받지 못했다는 이야기도
        덧붙였다. 특히 은연 중 대기업이나 해외 유수의 기업이 갖추고 있는
        시스템을 이상적인 방향이라고 여기는 경향이 컸고, 일부 기업에서는 인사나
        교육담당자를 채용할 때 대기업 경험이 있는 인사담당자를 찾아 육성
        시스템의 노하우를 적용하려는 시도를 하는 조직도 있었다.
      </div>
      <img src="../images/learning-body-image01.png" alt="본문 사진" />
      <div>
        90년대 이후, 세계가 무한 경쟁체제로 돌입하고 기업의 생산성과 성장을 위해
        '인재 육성'의 중요성이 대두되면서, 국내외 규모를 갖춘 기업은 인재원을
        중심으로 리더십을 포함한 각종 교육 프로그램에 대한 투자에 무척
        적극적이었다. 사내대학과 같은 과정이 개설되기도 했고, 기업교육
        전문회사와 컨설팅업체들과 함께 고가의 리더십 프로그램도 도입하는 등
        다양한 시도를 해 왔다. 이로 인해 어느 정도의 성과를 거둔 것은 부인할 수
        없지만 2020년 오늘 시점에서 냉정하게 평가해 본다면 사실 유명무실해져
        버린 것들도 적지 않다. 세상의 변화와 시대의 속도가 너무 빨라 교육과정을
        만들어 내고 시스템에 맞춘 리더를 육성해 내는 호흡과 현실 리더가 겪게
        되는 과제의 종류와 다양성의 격차가 나기 시작했기 때문이다. 그리고
        대기업의 인재 육성 시스템은 이를 주도하고 시행하는 '교육팀의 성과'와
        밀접히 연결되어 있을 수밖에 없기 때문에 실제 육성시스템의 프로세스와
        결과물의 많은 부분이 성과 측정을 위해 변질됐다는 부분도 부인할 수 없다.
      </div>
    </body>
`

**css**
`
/* Body */
/* 가로 사이즈 ! 전체 감살떄 참고 width: 1164px; */
.title-all {
    position:relative;
    text-align-last: center;
}
.head-title {
    display: center;
    color: var(--gray33);
    font-size: 28px;
    font-weight: 700;
}
.body-title {
    display: flex;
    color: var(--gray66);
}

.body-left-title {
    padding-left: 30px ;
    font-weight: 700;
    font-size: 16px;
    letter-spacing: -0.32px;
}

.body-right {
    align-items: end;
    .body-right-title {
        display: flex;
        gap: 20px;
        font-size: 14px;
        font-weight: 400;
        letter-spacing: -0.28px;
    }
}
`

**Comment by rebehayan** [comment]
주축, 교차축 정렬은 자식이 아닌 부모에 주셔야 합니다.
```css
.body-title {
   display: flex;
   color: var(--gray66);
   **justify-content:space-between;**
}
```
주축 정렬을 추가하시면되고,
```css
.body-right {
   align-items: end;
}
```
align-items는 교차축 정렬이므로 삭제해도 됩니다.
